export interface Subtitle {
  autoGenerated: boolean
  code: string
  mimeType: string
  name: string
  url: string
}

export interface BaseStream {
  bitrate: number
  codec: string
  format: string
  indexEnd: number
  indexStart: number
  initEnd: number
  initStart: number
  mimeType: string
  quality: string
  url: string
  videoOnly: boolean
}

export interface AudioStream extends BaseStream {}
export interface VideoStream extends BaseStream {
  fps: number
  height: number
  width: number
}

export interface RelatedStream {
  duration: number
  thumbnail: string
  title: string
  uploadedDate: string
  uploaderAvatar: string
  uploaderUrl: string
  uploaderVerified: boolean
  url: string
  views: number
}

export interface Video {
  audioStreams: AudioStream[]
  dash?: string
  description: string
  dislikes: number
  duration: number
  hls?: string
  lbryId: string
  likes: number
  livestream: boolean
  proxyUrl: string
  relatedStreams: RelatedStream[]
  subtitles: Subtitle[]
  thumbnailUrl: string
  title: string
  uploadDate: string
  uploader: string
  uploaderUrl: string
  uploaderVerified: boolean
  videoStreams: VideoStream[]
  views: number
}

export interface SearchVideo {
  url: string
  type: 'stream'
  title: string
  thumbnail: string
  uploaderName: string
  uploaderUrl: string
  uploaderAvatar: null
  uploadedDate: null
  shortDescription: null
  duration: number
  views: -1
  uploaded: -1
  uploaderVerified: false
  isShort: false
}

export interface SearchResults {
  items: SearchVideo[]
  nextpage: string
  suggestion: string
  corrected: boolean
}
